

# This file was *autogenerated* from the file DFR.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_2 = Integer(2)
n = _sage_const_8 
F. < w > = FiniteField(_sage_const_2  ** _sage_const_8 )

print(F)

w.multiplicative_order()

